version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: food-challenge
      POSTGRES_DB: order
      POSTGRES_PASSWORD: root

  app:
    depends_on: [db]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: food-challenge
      DB_PASSWORD: root