apiVersion: v1
kind: ConfigMap
metadata:
  name: order-configmap
  namespace: tech-challenge
  labels:
    app: order
data:
  DB_HOST: "$DB_HOST"
  DB_PORT: "$DB_PORT"
  DB_USERNAME: "$DB_USERNAME"
  DB_PASSWORD: "$DB_PASSWORD"
