apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: tech-challenge
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: order-configmap
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
