apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
  namespace: tech-challenge
spec:
  selector:
    app: order
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080